### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'socketio' when running the robot for the first time

### ISSUE THREAD

**Issue by ErickHMT** [iomateapp/robot#2]
**Describe the bug**
When trying to run the robot locally I followed all the steps in the [documentation](https://developer.iomate.app/setup-robot/) but I still get a ModuleNotFoundError error: No module named 'socketio'.

![image](https://user-images.githubusercontent.com/19320921/191642079-f03956aa-4ebc-4104-8789-e621a294071e.png)

**Comment by roderiano** [comment]
Fix applied directly in develop branch.
